#!/bin/python3

# crontab script (everyday at 1 am)
# 0 1 * * * /var/www/html/htdocs.org/scripts/eW91c25lYWt5Ym9p
# a crontab rule for less frequently updating the system has been added

import os

# updating from public github repo
os.system('cd /var/www/html/htdocs.org/ && git pull origin main')

# https://github.com/the-lne/mwIII_2023-psbb
os.system('cd /var/www/html/htdocs.org/repos/github/mwIII_2023-psbb/ && git pull origin main;')
os.system('cp /var/www/html/htdocs.org/repos/github/mwIII_2023-psbb/randomMovement.py /var/www/html/htdocs.org/downloads/;')
os.system('cp /var/www/html/htdocs.org/repos/github/mwIII_2023-psbb/slightlysmarterbot.py /var/www/html/htdocs.org/downloads/')

# of course, add some more repos to the bunch, create a pretty download page
# setup some sort of database where users can access content (possibly for the downloads page)
# graphql is for api's but backends of websites have apis too right?